# Generated by Django 3.1.5 on 2021-01-12 09:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0002_auto_20210112_0902'),
    ]

    operations = [
        migrations.RenameField(
            model_name='role',
            old_name='username',
            new_name='user',
        ),
    ]
