# Generated by Django 3.1.5 on 2021-01-12 09:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('web_app', '0003_auto_20210112_0906'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolehaspermisson',
            old_name='permission_id',
            new_name='permission',
        ),
        migrations.RenameField(
            model_name='rolehaspermisson',
            old_name='role_id',
            new_name='role',
        ),
        migrations.AlterField(
            model_name='role',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
